### ISSUE TITLE
Broken with streamlit 1.12

### ISSUE THREAD

**Issue by hsadok** [whitphx/streamlit-server-state#128]
The latest streamlit moved `lib/streamlit/server` to a different location in commit https://github.com/streamlit/streamlit/commit/ddfe5c02234d6e8eb5deb26c42605979f623e810

As a result this package is now broken.

**Comment by whitphx** [comment]
Thank you for the report!

**Comment by whitphx** [comment]
Dev note:
With this upgrade, the singleton instance of the server has been removed (`Server.get_current()` is no longer available).
We have to find an alternative that can be used to store a server-wide object.

**Comment by hsadok** [comment]
Thank you @whitphx for the library and for fixing this so quickly!
